sensors: 
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth/points  #/orb_slam2_rgbd/map_points /camera/depth/points
    max_range: 10.0
    frame_subsample: 1
    point_subsample: 1
